### ISSUE TITLE
Edit Illustration for Women in Tech

### ISSUE THREAD

**Issue by meinhoonharsh** [utkarshpathak2504/gdsc.github.io#4]
#### Description
The current Illustration looks good, but It does not follow the color scheme of google color. We can Improve this Illustration by
making something that depicts more about Web Development and It looks good there. Have a look at the Screenshots attached to get a better understanding 

#### Screenshots
How current Illustration looks 
![image](https://user-images.githubusercontent.com/64343449/136685199-e0573baa-b342-444d-a77e-1badf6142ada.png)

Illustration 
![Illustration](https://raw.githubusercontent.com/gdscrgpv/gdscrgpv/main/assets/img/cardillustrations/03.jpg)

#### Files
`/assets/img/cardillustration/03.jpg` - Illustration for Women in Tech

#### To Reproduce
- No Reproducing Steps
- just visit [https://gdscrgpv.github.io/gdscrgpv/](https://gdscrgpv.github.io/gdscrgpv/) to have a look at them

#### Tasks
- [ ] Update Illustration in `assets/img/cardillustrations/03.jpg`
Make sure the Dimensions of new Illustration will be 1:2

**Comment by atharvabhatt200** [comment]
Hello @meinhoonharsh, can you please assign me this issue? Thanks.
